Feature: PIN-5823 - delegated availability
pagopa/pdnd-interop-frontend pull request #1049
Opened 2024-12-19 09:03 UTC by alten-dturus

- Implemented new services and mutations
- Update `tenant.utils`
- Update `DelegationAvailabilityDrawer`
- Update `DelegationAvailabilityTab`

2025-01-30 16:09 UTC, Carminepo2 requested changes

2025-01-30 16:09 UTC, Carminepo2 commented on src/pages/DelegationsPage/DelegationsAvailabilityTab/DelegationAvailabilityDrawer.tsx
>    function handleClick() {
Let's make this more specific

```suggestion
  function handleSubmit() {
```

2025-01-30 16:09 UTC, Carminepo2 commented on src/pages/DelegationsPage/DelegationsAvailabilityTab/DelegationAvailabilityDrawer.tsx
> +    if (checkedConsumerDelegations != isAvailableConsumerDelegations) {
```suggestion
    if (checkedConsumerDelegations !== isAvailableConsumerDelegations) {
```

2025-01-30 16:09 UTC, Carminepo2 commented on src/pages/DelegationsPage/DelegationsAvailabilityTab/DelegationAvailabilityDrawer.tsx
>      if (checkedProducerDelegations != isAvailableProducerDelegations) {
```suggestion
    if (checkedProducerDelegations !== isAvailableProducerDelegations) {
```

2025-01-30 16:09 UTC, Carminepo2 commented on src/pages/DelegationsPage/DelegationsAvailabilityTab/DelegationAvailabilityTab.tsx
>    const isAvailableProducerDelegations = Boolean(producerDelegationsAvailability)
I would change the function `hasTenantGivenProducerDelegationAvailability` to return a boolean instead of doing it outside

2025-01-30 16:09 UTC, Carminepo2 commented on src/pages/DelegationsPage/DelegationsAvailabilityTab/DelegationAvailabilityTab.tsx
> +  const isAvailableConsumerDelegations = Boolean(consumerDelegationsAvailability)
Same here

2025-01-30 16:09 UTC, Carminepo2 commented on src/utils/tenant.utils.ts
> +}
```suggestion
export function hasTenantGivenConsumerDelegationAvailability(tenant: Tenant): boolean {
  return Boolean(tenant.features.find(
    (feature): feature is Extract<TenantFeature, { delegatedConsumer?: unknown }> =>
      Boolean('delegatedConsumer' in feature && feature.delegatedConsumer?.availabilityTimestamp)
  )?.delegatedConsumer?.availabilityTimestamp)
}
```

2025-02-04 13:33 UTC, borgesis95 approved these changes

2025-02-04 13:46 UTC, merged